// app/layout.tsx
import Header from "@/src/shared/components/layouts/main/header";
import Footer from "@/src/shared/components/layouts/main/footer";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";


export const metadata = {
  title: "Tran Hoang Anh Tu - Web Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased flex flex-col min-h-screen`}
      >
        <ThemeProvider
          attribute="class">
          <Header />
          <main>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
